<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="comp-Lenovo-V110-15ISK" name="SIP number test" tests="2" failures="0" timestamp="30 Sep 2020 11:02:59 GMT" time="11.729" errors="0">
  <testcase name="@BeforeTest setUp" time="0.0" classname="tests.AWSCallingClass">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at pom.Calling.launchAWS(Calling.java:74)
	at tests.AWSCallingClass.setUPAWS(AWSCallingClass.java:25)
	at tests.TestBase.setUp(TestBase.java:124)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 14 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeTest setUp -->
  <testcase name="@AfterTest tearDown" time="0.0" classname="tests.AWSCallingClass">
    <skipped/>
  </testcase> <!-- @AfterTest tearDown -->
  <testcase name="sipNumberCall" time="0.001" classname="tests.AWSCallingClass">
    <skipped/>
  </testcase> <!-- sipNumberCall -->
  <testcase name="sipNumberCall" time="0.005" classname="tests.AWSCallingClass">
    <skipped/>
  </testcase> <!-- sipNumberCall -->
</testsuite> <!-- SIP number test -->
